version: "3"
services:
    frontend:
        container_name: client
        build:
            context: ./client_react
            dockerfile: Dockerfile
        image: moraa/client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/src/app
        networks:
            - network
        depends_on:
            - backend
    backend:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: moraa/server
        ports:
            - "5001:5001"
        volumes:
            - ./server:/src/app
            - /src/app/config
        networks:
            - network
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - backend
networks:
    network:
        driver: bridge